[[rule]]
    regexs = [
        '.*a.*'
    ]
    clusters = [
        'local0'
    ]
    continue = true

[[rule]]
    regexs = [
        '.*b.*'
    ]
    clusters = [
        'local1'
    ]

[[rule]]
    regexs = [
        '^abc.*'
    ]
    prefixes = [
        'xyz',
        'poi'
    ]
    clusters = [
        'local1'
    ]
